import { useContext } from 'react';

import { CertificatesContext } from '../contexts/CertificatesContext';

export const useCertificatesContext = () => {
  const {
    filterUserId,
    setFilterUserId,
    fetchCertificates,
    certificates,
    users,
    loading,
    setLoading,
    handleDateFilter,
    selectedDateRange,
    cargo,
    setCargo,
    setSetor,
    setContrato,
    setor,
    contrato,
    jobs,
    contracts,
    sectors,
    updateDocument,
    openModalPhoto,
    photoId,
    handleOpenModalPhoto,
    handleCloseModalPhoto,
    employeeIdSelected,
    setEmployeeIdSelected,
    formik,
    getDaysBetweenDates,
    getUserSchedules,
    dates,
    statusJustificationValue,
    setStatusJustificationValue,
  } = useContext(CertificatesContext);

  return {
    filterUserId,
    setFilterUserId,
    fetchCertificates,
    certificates,
    users,
    loading,
    setLoading,
    handleDateFilter,
    selectedDateRange,
    cargo,
    setCargo,
    setSetor,
    setContrato,
    setor,
    contrato,
    jobs,
    contracts,
    sectors,
    updateDocument,
    openModalPhoto,
    photoId,
    handleOpenModalPhoto,
    handleCloseModalPhoto,
    employeeIdSelected,
    setEmployeeIdSelected,
    formik,
    getDaysBetweenDates,
    getUserSchedules,
    dates,
    statusJustificationValue,
    setStatusJustificationValue,
  };
};
